<a href="https://colab.research.google.com/github/Jovenstriker/neural-networks/blob/main/ActualMNISTNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
def sig(x):
  return 1/(1+np.exp(-x))
def sigDerv(x):
  return sig(x)*(1-sig(x))

def cost(actual,predicted):
  return np.average((actual-predicted)**2)
def costDerv(actual,predicted):
  return 2*(predicted-actual)/predicted.size

In [ ]:
from keras.datasets import mnist
# from keras.utils import np_utils
import keras.utils
# load MNIST from server
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# training data : 60000 samples
# reshape and normalize input data
x_train = x_train.reshape(x_train.shape[0], 1, 28*28)
x_train = x_train.astype('float32')
x_train /= 255
# encode output which is a number in range [0,9] into a vector of size 10
# e.g. number 3 will become [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
y_train = keras.utils.to_categorical(y_train)

# same for test data : 10000 samples
x_test = x_test.reshape(x_test.shape[0], 1, 28*28)
x_test = x_test.astype('float32')
x_test /= 255
y_test = keras.utils.to_categorical(y_test)

print(y_test.size)
print(x_test.size)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
100000
7840000


In [ ]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
class NeuralNetwork:
  def __init__(self):
    self.layers = []

  def add(self,layer):
    self.layers.append(layer)

  def train(self, input, actualOutput, trials):

    trialNumber = 0
    for x in range(trials): #Goes through each trial of practice
      success = 0
      total = 0
      for y in range(len(input)):
        output = input[y] #Technically first input (it's the data of the drawing)
        for z in self.layers:
          output = z.forward(output) #Goes through the layers, getting an successful (?) prediction
        error = costDerv(actualOutput[y],output)
        if (actualOutput[y].argmax()==output.argmax()): #Success counter
          success+=1
        total+=1
        for z in reversed(self.layers): #Backward propagation
          error = z.backward(error)
      trialNumber+=1
      if(total==0):
        print("Invalid, division by zero| Successes " + str(success))
      else:
        print("Trial: "+ str(trialNumber)+"|"+ str(success) + "/" + str(total) + "|Percentage:" +str(round(success/total,3))) #Success calculator




In [ ]:
class layer:
  def __init__(self,inputSize,outputSize): #i is input size, o is output size
    self.weights = np.random.rand(inputSize, outputSize) #Creates a i by o array of weights, the (0,2) represent connectetions between 3rd top neuron and next top neuron, etc
    self.bias = np.random.rand(1,outputSize) #Creates a 1 by o array of random biases [0,0.23,0.64,...]
  def forward(self,inputData):
    self.input = inputData
    self.output = sig(np.dot(self.input, self.weights) +self.bias) #self.output is an o by 1 array of outputs, activated by sig function
    return self.output
  def backward(self,outputError): #Output error is the gradient descent recursively given
    inputError = np.dot(outputError,self.weights.T)
    weightError = np.dot(self.input.T,outputError)
    self.weights -= weightError*.1
    self.bias -= outputError*.1
    return inputError*sigDerv(self.input) #returns the gradient descent deactivated of sig by chain rule

In [ ]:

print(x_train.shape)
print(y_train.shape)

(60000, 1, 784)
(60000, 10)


In [ ]:
net = NeuralNetwork()
net.add(layer(28*28,100))
net.add(layer(100,50))

net.add(layer(50,10))
# net.train(x_train[1000:2000], y_train[1000:2000], 75) #training the network
print(len(x_train[1000:2000]))
# print("Network is now trained")
for a in range(100):
  randomX = np.random.randint(0,58999)
  print("Test " + str(a))
  net.train(x_train[randomX:randomX+1000], y_train[randomX:randomX+1000],1) #Testing the output


1000
Test 0
Trial: 1|91/1000|Percentage:0.091
Test 1
Trial: 1|94/1000|Percentage:0.094
Test 2
Trial: 1|167/1000|Percentage:0.167
Test 3
Trial: 1|343/1000|Percentage:0.343
Test 4
Trial: 1|455/1000|Percentage:0.455
Test 5
Trial: 1|571/1000|Percentage:0.571
Test 6
Trial: 1|672/1000|Percentage:0.672
Test 7
Trial: 1|742/1000|Percentage:0.742
Test 8
Trial: 1|702/1000|Percentage:0.702
Test 9
Trial: 1|735/1000|Percentage:0.735
Test 10
Trial: 1|765/1000|Percentage:0.765
Test 11
Trial: 1|817/1000|Percentage:0.817
Test 12
Trial: 1|801/1000|Percentage:0.801
Test 13
Trial: 1|819/1000|Percentage:0.819
Test 14
Trial: 1|792/1000|Percentage:0.792
Test 15
Trial: 1|823/1000|Percentage:0.823
Test 16
Trial: 1|848/1000|Percentage:0.848
Test 17
Trial: 1|845/1000|Percentage:0.845
Test 18
Trial: 1|809/1000|Percentage:0.809
Test 19
Trial: 1|867/1000|Percentage:0.867
Test 20
Trial: 1|849/1000|Percentage:0.849
Test 21
Trial: 1|869/1000|Percentage:0.869
Test 22
Trial: 1|817/1000|Percentage:0.817
Test 23
Trial: 1|8

KeyboardInterrupt: 

In [ ]:
a=[0]*10
# a.insert(9,1)
a[9]=1
print(a)